extends: standard

overrides:
  -
    files: [ 'lib/**', 'index.mjs' ]
    parserOptions: { ecmaVersion: 2015 }

ignorePatterns:
  - demo/
  - dist/
  - benchmark/extra/

rules:
  camelcase: 0
  no-multi-spaces: 0
